[build]
  # Build command
  command = "npm run build"
  
  # Publish directory (where Vite outputs the built files)
  publish = "dist"
  
  # Environment variables (you'll need to set these in Netlify dashboard)
  [build.environment]
    NODE_VERSION = "18"

# Redirects for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache index.html for shorter time
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[dev]
  targetPort = 5174

# Scheduled Functions
[functions."update-days-at-location"]
  schedule = "0 1 * * *"  # Run daily at 1:00 AM UTC